package ru.equifax.hbn;
// default package
// Generated 21.10.2017 15:03:38 by Hibernate Tools 5.2.3.Final

/**
 * ActorInfo generated by hbm2java
 */
public class ActorInfo implements java.io.Serializable {

	private ActorInfoId id;

	public ActorInfo() {
	}

	public ActorInfo(ActorInfoId id) {
		this.id = id;
	}

	public ActorInfoId getId() {
		return this.id;
	}

	public void setId(ActorInfoId id) {
		this.id = id;
	}

}
