package ru.equifax.hbn;
// default package
// Generated 21.10.2017 15:03:38 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.ColumnTransformer;

/**
 * Address generated by hbm2java
 */
//@Entity
//@Table(name="address", schema="sakila")
public class Address implements java.io.Serializable {

	
//	@Column(name="address_id")
//	@ColumnTransformer(forColumn="address_id",
//	read="address_id + 5.0",
//	write="? + 25.0")
	public Double getAddressD(){
		return this.addressD;
	}
	public void setAddressD(Double addressD) {
		this.addressD = addressD;
	}
	private Double addressD;
//	@Column(name="address_id")
	private Integer address_id;
	/*@Column(name="")
	private City city;*/
//	@Column(name="address")
	private String address;
//	@Column(name="address2")
	private String address2;
//	@Column(name="district")
	private String district;
//	@Column(name="postal_code")
	private String postalCode;
//	@Column(name="phone")
	private String phone;
//	@Column(name="location")
	private byte[] location;
//	@Column(name="last_update")
	private Date lastUpdate;
	private Set staffs = new HashSet(0);
	private Set customers = new HashSet(0);
	private Set stores = new HashSet(0);

	public Address() {
	}
	public Address(Double addressD, Integer address_id ,String address, String address2, String district, String postalCode, String phone,
			byte[] location, Date lastUpdate) {
		this.addressD = addressD;
		this.address_id = address_id;
		this.address = address;
		this.address2 = address2;
		this.district = district;
		this.postalCode = postalCode;
		this.phone = phone;
		this.location = location;
		this.lastUpdate = lastUpdate;
		
	}
	/*
	public Address(City city, String address, String district, String phone, byte[] location, Date lastUpdate) {
		this.city = city;
		this.address = address;
		this.district = district;
		this.phone = phone;
		this.location = location;
		this.lastUpdate = lastUpdate;
	}

	public Address(City city, String address, String address2, String district, String postalCode, String phone,
			byte[] location, Date lastUpdate, Set staffs, Set customers, Set stores) {
		this.city = city;
		this.address = address;
		this.address2 = address2;
		this.district = district;
		this.postalCode = postalCode;
		this.phone = phone;
		this.location = location;
		this.lastUpdate = lastUpdate;
		this.staffs = staffs;
		this.customers = customers;
		this.stores = stores;
	}
	*/
	
	
	public Integer getAddressId(){
		return this.address_id;
	}
	
	public void setAddressId(Integer address_id) {
		this.address_id = address_id;
	}
	
	

	/*public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}*/

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public byte[] getLocation() {
		return this.location;
	}

	public void setLocation(byte[] location) {
		this.location = location;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}
/*
	public Set getStaffs() {
		return this.staffs;
	}

	public void setStaffs(Set staffs) {
		this.staffs = staffs;
	}

	public Set getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set customers) {
		this.customers = customers;
	}

	public Set getStores() {
		return this.stores;
	}

	public void setStores(Set stores) {
		this.stores = stores;
	}
*/
	
}
