package ru.equifax.hbn;
// default package
// Generated 21.10.2017 15:03:38 by Hibernate Tools 5.2.3.Final

/**
 * CustomerList generated by hbm2java
 */
public class CustomerList implements java.io.Serializable {

	private CustomerListId id;

	public CustomerList() {
	}

	public CustomerList(CustomerListId id) {
		this.id = id;
	}

	public CustomerListId getId() {
		return this.id;
	}

	public void setId(CustomerListId id) {
		this.id = id;
	}

}
