package ru.equifax.hbn;
// default package
// Generated 21.10.2017 15:03:38 by Hibernate Tools 5.2.3.Final

/**
 * FilmList generated by hbm2java
 */
public class FilmList implements java.io.Serializable {

	private FilmListId id;

	public FilmList() {
	}

	public FilmList(FilmListId id) {
		this.id = id;
	}

	public FilmListId getId() {
		return this.id;
	}

	public void setId(FilmListId id) {
		this.id = id;
	}

}
