package ru.equifax.hbn;
// default package
// Generated 21.10.2017 15:03:38 by Hibernate Tools 5.2.3.Final

/**
 * NicerButSlowerFilmList generated by hbm2java
 */
public class NicerButSlowerFilmList implements java.io.Serializable {

	private NicerButSlowerFilmListId id;

	public NicerButSlowerFilmList() {
	}

	public NicerButSlowerFilmList(NicerButSlowerFilmListId id) {
		this.id = id;
	}

	public NicerButSlowerFilmListId getId() {
		return this.id;
	}

	public void setId(NicerButSlowerFilmListId id) {
		this.id = id;
	}

}
