package ru.equifax.hbn;
// default package
// Generated 21.10.2017 15:03:38 by Hibernate Tools 5.2.3.Final

/**
 * StaffList generated by hbm2java
 */
public class StaffList implements java.io.Serializable {

	private StaffListId id;

	public StaffList() {
	}

	public StaffList(StaffListId id) {
		this.id = id;
	}

	public StaffListId getId() {
		return this.id;
	}

	public void setId(StaffListId id) {
		this.id = id;
	}

}
